### ISSUE TITLE
Create getMovableEntries method in Grid

### ISSUE THREAD

**Issue by RouNNdeL** [APRO-Project/app#22]
Create a method that given the `PlayerNum` returns a `List<GridEntry>` that contains entries with at least one move available.

**Comment by 8ru73u5** [comment]
This would make caching possible moves pointless because it forces the game to calculate allowed moves and captures for each piece on the `Grid` every turn.

**Comment by RouNNdeL** [comment]
The AI is going to require all available moves anyway. So caching might have been the wrong approach after all. @BWalusiak is that right?

**Comment by 8ru73u5** [comment]
Or maybe we could cache available moves for human players only? Seems logical to me, as it would save some processing power.

**Comment by RouNNdeL** [comment]
Still, we'd like to be able to show the user which pieces are movable. That'd greatly improve UX.
