### ISSUE TITLE
Missing `mandatory_captures` option in `Preferences`

### ISSUE THREAD

**Issue by 8ru73u5** [APRO-Project/app#27]
Please add it to the `Preferences` as it's somewhat important optional rule in checkers.

**Comment by RouNNdeL** [comment]
What should the default values be?

**Comment by 8ru73u5** [comment]
It should be `true` as in international checkers.

Also I would suggest adding another option: `strict_mandatory_captures`, which would allow only the longest captures to be executed. What do you think?

**Comment by RouNNdeL** [comment]
I think that mandatory captures already implies the longest available captures.  It does not make sense to over-complicate the settings.
