### ISSUE TITLE
Non informative class and method names and duplicate/invalid code

### ISSUE THREAD

**Issue by 8ru73u5** [APRO-Project/app#46]
Class names `Tree` and `Node` are not informative thus they should be renamed or placed in a separate package with an informative name suggesting its purpose of existence.

Also, in `Grid` there is method called `getValue()` which also has non informative name and I insist on renaming it to something better.

Furthermore, `Grid` methods `won()` and `lost()` are identical so I suggest including code from one of them in another or making just one method that does it all.

Besides, what about draws? When the player hasn't got any more moves to make it doesn't necessarily imply his lost - it can be a draw, given the other player also can have no movable pieces. It should be taken into account when rewriting those methods.

**Comment by 8ru73u5** [comment]
I will handle the win/lose/draw situation as I'm responsible for the game logic but please make sure to fix those other problems.

**Comment by RouNNdeL** [comment]
I'd recommend placing all AI related classes in their own package (ex. `game.ai`). As well as moving existing game logic classes to a new package (ex. `game.logic`).
